# Generated by Django 3.2.20 on 2023-09-21 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decode_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newblog',
            name='author',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
