# Generated by Django 3.2.20 on 2023-09-23 14:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decode_blog', '0002_newblog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newblog',
            options={'verbose_name': 'Newlog', 'verbose_name_plural': 'NewBlogs'},
        ),
        migrations.AddField(
            model_name='newblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 20, 36, 27, 21240)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 9, 23, 20, 36, 27, 36876))),
                ('blog', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='decode_blog.newblog')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_images', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
