# Generated by Django 3.2.20 on 2023-10-01 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode_blog', '0020_auto_20231001_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editblog',
            options={'verbose_name': 'Editlog', 'verbose_name_plural': 'EditBlogs'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 11, 57, 51, 643303)),
        ),
        migrations.AlterField(
            model_name='editblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 11, 57, 51, 643303)),
        ),
        migrations.AlterField(
            model_name='newblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 11, 57, 51, 643303)),
        ),
    ]
