# Generated by Django 3.2.20 on 2023-10-01 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode_blog', '0022_auto_20231001_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 12, 17, 15, 480189)),
        ),
        migrations.AlterField(
            model_name='editblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 12, 17, 15, 478572)),
        ),
        migrations.AlterField(
            model_name='newblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 12, 17, 15, 478572)),
        ),
    ]
