# Generated by Django 3.2.20 on 2023-10-01 10:26

import datetime
import decode_blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decode_blog', '0023_auto_20231001_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditBlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=decode_blog.models.uniq_name_upload)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 10, 1, 16, 26, 28, 50630))),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='decode_blog.category')),
            ],
            options={
                'verbose_name': 'Editlog',
                'verbose_name_plural': 'EditBlogs',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 16, 26, 28, 50630)),
        ),
        migrations.AlterField(
            model_name='newblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 16, 26, 28, 50630)),
        ),
        migrations.DeleteModel(
            name='EditBlog',
        ),
    ]
