# Generated by Django 3.2.20 on 2023-10-01 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode_blog', '0024_auto_20231001_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 16, 33, 46, 245518)),
        ),
        migrations.AlterField(
            model_name='editblogmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 16, 33, 46, 245518)),
        ),
        migrations.AlterField(
            model_name='newblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 16, 33, 46, 245518)),
        ),
    ]
