# Generated by Django 3.2.20 on 2023-10-02 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode_blog', '0025_auto_20231001_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 18, 33, 53, 890908)),
        ),
        migrations.AlterField(
            model_name='newblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 18, 33, 53, 890404)),
        ),
        migrations.DeleteModel(
            name='EditBlogModel',
        ),
    ]
